# Generated by Django 5.2.7 on 2025-11-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('serialnumber', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('stock', models.IntegerField()),
                ('price', models.IntegerField()),
                ('warranty', models.CharField(max_length=50)),
                ('distributer', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.TextField(unique=True)),
                ('category', models.CharField(default='Phone', max_length=50)),
            ],
        ),
    ]
