# Generated by Django 5.2.7 on 2025-11-14 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_scrapedproduct'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='scrapedproduct',
            table='scraped_products',
        ),
    ]
