# Generated by Django 5.2.7 on 2025-11-14 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_fix_missing_brand_column'),
        ('catalog', '0004_alter_scrapedproduct_table'),
    ]

    operations = [
    ]
