# Generated by Django 5.2.7 on 2025-11-14 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_merge_20251114_1951'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='scrapedproduct',
            table=None,
        ),
    ]
