# Generated by Django 5.2.8 on 2025-11-27 12:25

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_review_wishlistitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_ids', django.contrib.postgres.fields.ArrayField(
                    base_field=models.IntegerField(), blank=True, default=list, size=None
                )),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='wishlist',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
        ),
    ]
