# Generated by Django 5.2.8 on 2025-11-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_delete_wishlistitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
