# Generated by Django 5.2.8 on 2025-12-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_review_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
