# Generated by Django 5.2.8 on 2025-12-20 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_scrapedproduct_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedproduct',
            name='discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scrapedproduct',
            name='discount_percentage',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
