# Generated by Django 5.2.9 on 2025-12-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_scrapedproduct_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedproduct',
            name='cloudinary_image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
