# Generated by Django 5.2.8 on 2025-12-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0017_scrapedproduct_cost"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="scrapedproduct",
                    name="cloudinary_image_url",
                    field=models.TextField(blank=True, null=True),
                ),
            ],
        ),
    ]
