# Generated by Django 5.2.8 on 2025-11-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_card_last_four_order_payment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="email_sent",
            field=models.BooleanField(default=False),
        ),
    ]

