# Generated by Django 5.1.3 on 2024-12-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_card_last_four_order_payment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="email_sent",
            field=models.BooleanField(default=False),
        ),
    ]
