# Generated by Django 5.2.7 on 2025-12-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_invoice_email_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="delivery_address",
            field=models.TextField(db_column="delivery_address"),
        ),
        migrations.RenameField(
            model_name="delivery",
            old_name="delivery_address",
            new_name="_delivery_address_encrypted",
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_address",
            field=models.TextField(db_column="delivery_address"),
        ),
        migrations.RenameField(
            model_name="order",
            old_name="delivery_address",
            new_name="_delivery_address_encrypted",
        ),
    ]
