# Generated by Django 5.2.9 on 2025-12-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_refundrequest_refunditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundrequest',
            name='manager_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
