# Generated by Django 5.2.8 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='cloudinary_attachment_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]

