# Generated by Django 5.2.7 on 2025-12-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration to add multi-role support to user profiles.
    
    This migration:
    1. Renames CustomerProfile to UserProfile (preserves existing data)
    2. Adds role field with choices for different user types
    3. Adds updated_at timestamp field
    4. Updates model Meta options
    """

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        # Step 1: Rename the model from CustomerProfile to UserProfile
        migrations.RenameModel(
            old_name="CustomerProfile",
            new_name="UserProfile",
        ),
        
        # Step 2: Add the role field with 'customer' as default
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("sales_manager", "Sales Manager"),
                    ("product_manager", "Product Manager"),
                    ("support_agent", "Support Agent"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
        
        # Step 3: Add the updated_at timestamp field
        migrations.AddField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        
        # Step 4: Update the model Meta options
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
