# Generated by Django 5.2.7 on 2025-12-15 19:49
# Modified to properly handle field renames and encryption changes

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_add_user_role_support"),
    ]

    operations = [
        # Step 1: Rename fields at ORM level while keeping same db_column
        # This preserves existing data in the database
        
        # Rename home_address to _home_address_encrypted
        migrations.RenameField(
            model_name="userprofile",
            old_name="home_address",
            new_name="_home_address_encrypted",
        ),
        
        # Rename tax_id to _tax_id_encrypted
        migrations.RenameField(
            model_name="userprofile",
            old_name="tax_id",
            new_name="_tax_id_encrypted",
        ),
        
        # Rename card_number to _card_number_encrypted
        migrations.RenameField(
            model_name="userprofile",
            old_name="card_number",
            new_name="_card_number_encrypted",
        ),
        
        # Step 2: Alter fields to match new definitions (larger max_length for encrypted data)
        migrations.AlterField(
            model_name="userprofile",
            name="_home_address_encrypted",
            field=models.TextField(blank=True, db_column="home_address"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="_tax_id_encrypted",
            field=models.CharField(blank=True, db_column="tax_id", max_length=255),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="_card_number_encrypted",
            field=models.CharField(blank=True, db_column="card_number", max_length=255),
        ),
    ]
